Traceback (most recent call last):
  File "/home/runner/workspace/src/manage.py", line 22, in <module>
    main()
  File "/home/runner/workspace/src/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/home/runner/workspace/src/apps/clients/apps.py", line 9, in ready
    import apps.clients.signals  # Asegúrate de que esto cargue las señales al iniciar
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/src/apps/clients/signals.py", line 8, in <module>
    from ..core.telegram_notifier import send_telegram_message
  File "/home/runner/workspace/src/apps/core/telegram_notifier.py", line 14, in <module>
    bot = Bot(token=TELEGRAM_BOT_TOKEN)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/telegram/_bot.py", line 243, in __init__
    HTTPXRequest() if get_updates_request is None else get_updates_request,
    ^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 115, in __init__
    self._client = self._build_client()
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 126, in _build_client
    return httpx.AsyncClient(**self._client_kwargs)  # type: ignore[arg-type]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AsyncClient.__init__() got an unexpected keyword argument 'proxies'