➜  src git:(main) ✗ python manage.py makemigrations                     
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0013_reservation_discount_code_used, 0022_reservation_discount_code_used in reservation).
To fix them run 'python manage.py makemigrations --merge'
➜  src git:(main) ✗ python manage.py makemigrations --merge
Merging reservation
  Branch 0013_reservation_discount_code_used
    - Add field comentarios_reservas to reservation
    - Add field fbc to reservation
    - Add field fbclid to reservation
    - Add field fbp to reservation
    - Add field ip_cliente to reservation
    - Add field late_check_out_date to reservation
    - Add field late_checkout to reservation
    - Add field payment_confirmed to reservation
    - Add field payment_voucher_deadline to reservation
    - Add field payment_voucher_uploaded to reservation
    - Add field points_redeemed to reservation
    - Add field referer to reservation
    - Add field status to reservation
    - Add field user_agent to reservation
    - Add field utm_campaign to reservation
    - Add field utm_medium to reservation
    - Add field utm_source to reservation
    - Alter field file on rentalreceipt
    - Alter field origin on reservation
    - Add field discount_code_used to reservation
  Branch 0022_reservation_discount_code_used
    - Add field late_check_out_date to reservation
    - Add field late_checkout to reservation
    - Alter field file on rentalreceipt
    - Add field comentarios_reservas to reservation
    - Add field fbclid to reservation
    - Add field ip_cliente to reservation
    - Add field referer to reservation
    - Add field user_agent to reservation
    - Add field utm_campaign to reservation
    - Add field utm_medium to reservation
    - Add field utm_source to reservation
    - Add field fbp to reservation
    - Add field fbc to reservation
    - Add field points_redeemed to reservation
    - Add field status to reservation
    - Alter field origin on reservation
    - Add field payment_confirmed to reservation
    - Add field payment_voucher_deadline to reservation
    - Add field payment_voucher_uploaded to reservation
    - Alter field status on reservation
    - Add field comentarios_reservas to reservation
    - Add field fbc to reservation
    - Add field fbclid to reservation
    - Add field fbp to reservation
    - Add field ip_cliente to reservation
    - Add field late_check_out_date to reservation
    - Add field late_checkout to reservation
    - Add field payment_confirmed to reservation
    - Add field payment_voucher_deadline to reservation
    - Add field payment_voucher_uploaded to reservation
    - Add field points_redeemed to reservation
    - Add field referer to reservation
    - Add field status to reservation
    - Add field user_agent to reservation
    - Add field utm_campaign to reservation
    - Add field utm_medium to reservation
    - Add field utm_source to reservation
    - Alter field file on rentalreceipt
    - Alter field origin on reservation
    - Add field discount_code_used to reservation

Merging will only work if the operations printed above do not conflict
with each other (working on different fields or models)
Should these migration branches be merged? [y/N] y

Created new merge migration /srv/casaaustin/api-casa-austin/src/apps/reservation/migrations/0023_merge_20250817_0528.py
➜  src git:(main) ✗ python manage.py migrate               
Operations to perform:
  Apply all migrations: accounts, admin, auth, clients, contenttypes, property, reservation, sessions
Running migrations:
  Applying reservation.0013_reservation_discount_code_used...Traceback (most recent call last):
  File "/home/almalinux/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/almalinux/.local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/almalinux/.local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/almalinux/.local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/almalinux/.local/lib/python3.9/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1060, "Duplicate column name 'discount_code_used'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/casaaustin/api-casa-austin/src/manage.py", line 22, in <module>
    main()
  File "/srv/casaaustin/api-casa-austin/src/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/almalinux/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/almalinux/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/almalinux/.local/lib/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/almalinux/.local/lib/python3.9/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/almalinux/.local/lib/python3.9/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/home/almalinux/.local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
  File "/home/almalinux/.local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/home/almalinux/.local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/home/almalinux/.local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/almalinux/.local/lib/python3.9/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/home/almalinux/.local/lib/python3.9/site-packages/django/db/migrations/operations/fields.py", line 108, in database_forwards
    schema_editor.add_field(
  File "/home/almalinux/.local/lib/python3.9/site-packages/django/db/backends/mysql/schema.py", line 107, in add_field
    super().add_field(model, field)
  File "/home/almalinux/.local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 713, in add_field
    self.execute(sql, params)
  File "/home/almalinux/.local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 201, in execute
    cursor.execute(sql, params)
  File "/home/almalinux/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/almalinux/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/almalinux/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/almalinux/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/almalinux/.local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/almalinux/.local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/almalinux/.local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/almalinux/.local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/almalinux/.local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/almalinux/.local/lib/python3.9/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1060, "Duplicate column name 'discount_code_used'")