Operations to perform:
  Apply all migrations: accounts, admin, auth, clients, contenttypes, property, reservation, sessions
Running migrations:
  Applying reservation.0012_reservation_comentarios_reservas_reservation_fbc_and_more... OK
  Applying property.0011_property_banos_property_caracteristicas_and_more... OK
  Applying clients.0013_referralpointsconfig_clients_comentarios_clientes_and_more... OK
Watching for file changes with StatReloader
INFO 2025-08-15 15:45:10,538 autoreload 5788 139741987990720 Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 15, 2025 - 15:45:10
Django version 4.2.11, using settings 'config.settings'
Starting development server at http://0.0.0.0:5000/
Quit the server with CONTROL-C.

Invalid HTTP_HOST header: 'ac4f8fba-15fb-4014-8235-6b8a0be1d56e-00-3l5w4ss0bb8fk.spock.replit.dev'. You may need to add 'ac4f8fba-15fb-4014-8235-6b8a0be1d56e-00-3l5w4ss0bb8fk.spock.replit.dev' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'ac4f8fba-15fb-4014-8235-6b8a0be1d56e-00-3l5w4ss0bb8fk.spock.replit.dev'. You may need to add 'ac4f8fba-15fb-4014-8235-6b8a0be1d56e-00-3l5w4ss0bb8fk.spock.replit.dev' to ALLOWED_HOSTS.
ERROR 2025-08-15 15:45:11,680 exception 5788 139741890778816 Invalid HTTP_HOST header: 'ac4f8fba-15fb-4014-8235-6b8a0be1d56e-00-3l5w4ss0bb8fk.spock.replit.dev'. You may need to add 'ac4f8fba-15fb-4014-8235-6b8a0be1d56e-00-3l5w4ss0bb8fk.spock.replit.dev' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'ac4f8fba-15fb-4014-8235-6b8a0be1d56e-00-3l5w4ss0bb8fk.spock.replit.dev'. You may need to add 'ac4f8fba-15fb-4014-8235-6b8a0be1d56e-00-3l5w4ss0bb8fk.spock.replit.dev' to ALLOWED_HOSTS.
Bad Request: /
WARNING 2025-08-15 15:45:11,708 log 5788 139741890778816 Bad Request: /
[15/Aug/2025 15:45:11] "GET / HTTP/1.1" 400 171050