ImproperlyConfigured at /api/v1/events/activity-feed/
Field name `icon` is not valid for model `ActivityFeed`.
Request Method:	GET
Request URL:	http://api.casaaustin.pe/api/v1/events/activity-feed/
Django Version:	4.2
Exception Type:	ImproperlyConfigured
Exception Value:	
Field name `icon` is not valid for model `ActivityFeed`.
Exception Location:	/home/almalinux/.local/lib/python3.9/site-packages/rest_framework/serializers.py, line 1340, in build_unknown_field
Raised during:	apps.events.views.ActivityFeedView
Python Executable:	/usr/bin/python3
Python Version:	3.9.19
Python Path:	
['/srv/casaaustin/api-casa-austin/src',
 '/home/almalinux/.local/bin',
 '/usr/lib64/python39.zip',
 '/usr/lib64/python3.9',
 '/usr/lib64/python3.9/lib-dynload',
 '/home/almalinux/.local/lib/python3.9/site-packages',
 '/usr/local/lib64/python3.9/site-packages',
 '/usr/local/lib/python3.9/site-packages',
 '/usr/lib64/python3.9/site-packages',
 '/usr/lib/python3.9/site-packages']
Server time:	Sun, 21 Sep 2025 04:40:20 -0500
Traceback Switch to copy-and-paste view
/home/almalinux/.local/lib/python3.9/site-packages/django/core/handlers/exception.py, line 55, in inner
                response = get_response(request) …
Local vars
/home/almalinux/.local/lib/python3.9/site-packages/django/core/handlers/base.py, line 197, in _get_response
                response = wrapped_callback(request, *callback_args, **callback_kwargs) …
Local vars
/home/almalinux/.local/lib/python3.9/site-packages/django/views/decorators/csrf.py, line 56, in wrapper_view
        return view_func(*args, **kwargs) …
Local vars
/home/almalinux/.local/lib/python3.9/site-packages/django/views/generic/base.py, line 104, in view
            return self.dispatch(request, *args, **kwargs) …
Local vars
/home/almalinux/.local/lib/python3.9/site-packages/rest_framework/views.py, line 509, in dispatch
            response = self.handle_exception(exc) …
Local vars
/home/almalinux/.local/lib/python3.9/site-packages/rest_framework/views.py, line 469, in handle_exception
            self.raise_uncaught_exception(exc) …
Local vars
/home/almalinux/.local/lib/python3.9/site-packages/rest_framework/views.py, line 480, in raise_uncaught_exception
        raise exc 